-- MySQL Script generated by MySQL Workbench
-- 06/22/15 14:04:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `acc_id` INT(3) NOT NULL AUTO_INCREMENT COMMENT '',
  `acc_name` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `main_wallet_id` INT NULL COMMENT '',
  `active_email` VARCHAR(45) NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  PRIMARY KEY (`acc_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wallet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`wallet` ;

CREATE TABLE IF NOT EXISTS `mydb`.`wallet` (
  `wallet_id` INT(3) NOT NULL AUTO_INCREMENT COMMENT '',
  `acc_id` INT(3) NOT NULL COMMENT '',
  `wallet_name` VARCHAR(45) CHARACTER SET 'utf8mb4' NULL COMMENT '',
  `current_money` INT NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  PRIMARY KEY (`wallet_id`)  COMMENT '',
  INDEX `fk_wallet_account_idx` (`acc_id` ASC)  COMMENT '',
  CONSTRAINT `fk_wallet_account`
    FOREIGN KEY (`acc_id`)
    REFERENCES `mydb`.`account` (`acc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `cate_id` INT(3) NOT NULL AUTO_INCREMENT COMMENT '',
  `cate_name` VARCHAR(45) CHARACTER SET 'utf8mb4' NULL COMMENT '',
  `rep_image` VARCHAR(45) NULL COMMENT '',
  `purpose` TINYINT(1) NULL COMMENT '',
  `note` TEXT CHARACTER SET 'utf8mb4' NULL COMMENT '',
  PRIMARY KEY (`cate_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`use_money`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`use_money` ;

CREATE TABLE IF NOT EXISTS `mydb`.`use_money` (
  `use_money_id` INT(3) NOT NULL AUTO_INCREMENT COMMENT '',
  `wallet_wallet_id` INT(3) NOT NULL COMMENT '',
  `category_cate_id` INT(3) NOT NULL COMMENT '',
  `wallet_id` INT(3) NULL COMMENT '',
  `cate_id` INT(3) NULL COMMENT '',
  `amount` INT NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  PRIMARY KEY (`use_money_id`)  COMMENT '',
  INDEX `fk_use_money_wallet1_idx` (`wallet_wallet_id` ASC)  COMMENT '',
  INDEX `fk_use_money_category1_idx` (`category_cate_id` ASC)  COMMENT '',
  CONSTRAINT `fk_use_money_wallet1`
    FOREIGN KEY (`wallet_wallet_id`)
    REFERENCES `mydb`.`wallet` (`wallet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_use_money_category1`
    FOREIGN KEY (`category_cate_id`)
    REFERENCES `mydb`.`category` (`cate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
