-- MySQL Script generated by MySQL Workbench
-- 06/25/15 08:35:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema moneylover
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `moneylover` ;

-- -----------------------------------------------------
-- Schema moneylover
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moneylover` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `moneylover` ;

-- -----------------------------------------------------
-- Table `moneylover`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moneylover`.`users` ;

CREATE TABLE IF NOT EXISTS `moneylover`.`users` (
  `id` INT(3) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(256) NOT NULL COMMENT '',
  `current_wallet_id` INT NULL COMMENT '',
  `activated` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `token` VARCHAR(256) NULL COMMENT '',
  `modified` DATETIME NULL COMMENT '',
  `created` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moneylover`.`wallets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moneylover`.`wallets` ;

CREATE TABLE IF NOT EXISTS `moneylover`.`wallets` (
  `id` INT(3) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT(3) NOT NULL COMMENT '',
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL COMMENT '',
  `balance` INT NULL COMMENT '',
  `created` DATETIME NULL COMMENT '',
  `modified` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_wallet_account_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_wallet_account`
    FOREIGN KEY (`user_id`)
    REFERENCES `moneylover`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moneylover`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moneylover`.`categories` ;

CREATE TABLE IF NOT EXISTS `moneylover`.`categories` (
  `id` INT(3) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT(3) NOT NULL COMMENT '',
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL COMMENT '',
  `image` VARCHAR(45) NOT NULL COMMENT '',
  `purpose` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `note` TEXT CHARACTER SET 'utf8mb4' NULL COMMENT '',
  `categoriescol` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_categories_users1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_categories_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `moneylover`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moneylover`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moneylover`.`transactions` ;

CREATE TABLE IF NOT EXISTS `moneylover`.`transactions` (
  `id` INT(3) NOT NULL AUTO_INCREMENT COMMENT '',
  `wallet_id` INT(3) NOT NULL COMMENT '',
  `category_id` INT(3) NOT NULL COMMENT '',
  `amount` INT NULL COMMENT '',
  `modified` DATETIME NULL COMMENT '',
  `created` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_use_money_wallet1_idx` (`wallet_id` ASC)  COMMENT '',
  INDEX `fk_use_money_category1_idx` (`category_id` ASC)  COMMENT '',
  CONSTRAINT `fk_use_money_wallet1`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `moneylover`.`wallets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_use_money_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `moneylover`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
