-- MySQL Script generated by MySQL Workbench
-- 06/22/15 18:18:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT(3) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(256) NOT NULL COMMENT '',
  `current_wallet_id` INT NULL COMMENT '',
  `activated` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `token` VARCHAR(256) NULL COMMENT '',
  `modified` DATETIME NULL COMMENT '',
  `created` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wallets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`wallets` ;

CREATE TABLE IF NOT EXISTS `mydb`.`wallets` (
  `id` INT(3) NOT NULL AUTO_INCREMENT COMMENT '',
  `acc_id` INT(3) NOT NULL COMMENT '',
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' NULL COMMENT '',
  `balance_money` INT NULL COMMENT '',
  `created` DATETIME NULL COMMENT '',
  `modified` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_wallet_account_idx` (`acc_id` ASC)  COMMENT '',
  CONSTRAINT `fk_wallet_account`
    FOREIGN KEY (`acc_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id` INT(3) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL COMMENT '',
  `image` VARCHAR(45) NOT NULL COMMENT '',
  `purpose` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  `note` TEXT CHARACTER SET 'utf8mb4' NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transactions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transactions` (
  `id` INT(3) NOT NULL AUTO_INCREMENT COMMENT '',
  `wallet_id` INT(3) NOT NULL COMMENT '',
  `cate_id` INT(3) NOT NULL COMMENT '',
  `amount` INT NULL COMMENT '',
  `modified` DATETIME NULL COMMENT '',
  `created` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_use_money_wallet1_idx` (`wallet_id` ASC)  COMMENT '',
  INDEX `fk_use_money_category1_idx` (`cate_id` ASC)  COMMENT '',
  CONSTRAINT `fk_use_money_wallet1`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `mydb`.`wallets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_use_money_category1`
    FOREIGN KEY (`cate_id`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
